# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrQJ-Cr6y8Vwx0Fk64vZTWwwEdB5i71D
"""


# Hocam biz Google Colab üzerinden T4 GPU kullanarak kodun 2.00-3.00 dakika arasında çalıştığını gözlemledik.
# Accuracy skorumuzu 96.80-97.10 aralığında aldık.

# Prompts used:
# 1. "Suggest a faster alternative to ResNet50 for fracture detection under 5 minutes runtime limit on T4 GPU."
# 2. "Write a function to fix all random seeds in PyTorch to ensure identical results in every run."

import os
import time
import random
import shutil
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, Subset
from sklearn.model_selection import KFold
import numpy as np

# --- Rastgeleliği (Randomness) sağladık resimlerin benzer sırayla öğrenilebilmesi için. (for randomness control) ---
def set_seed(seed=42):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)


if os.path.exists('/content/data'):
    DATA_DIR = '/content/data'
else:
    DATA_DIR = './data'

print(f"Secilen Veri Yolu: {DATA_DIR}")

# --- TEMİZLİKÇİ: .ipynb_checkpoints SİLİCİ kendi bilgisayarımızda boyle bir hata aldığımız için ekledik hocam sizdede bu hata tekrarlanmasın diye  ---
# Bu kısım hatayı önler. Gizli Colab klasörünü siler.
checkpoint_path = os.path.join(DATA_DIR, '.ipynb_checkpoints')
if os.path.exists(checkpoint_path):
    try:
        shutil.rmtree(checkpoint_path)
        print("Sistem klasörü (.ipynb_checkpoints) temizlendi, hata önlendi.")
    except Exception as e:
        print(f"Uyarı: Checkpoint silinemedi, devam ediliyor. ({e})")

# --- HİPERPARAMETRELER ---
BATCH_SIZE = 32
NUM_EPOCHS = 12 #süremiz arttığı için yüksek accurcy için epochu artırdık hocam 8 den 12 ye.(we increase  epochs to 12 for better accuracy)
K_FOLDS = 10

def get_model(device):
    model = models.resnet34(weights=models.ResNet34_Weights.DEFAULT)
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, 2)
    return model.to(device)

def main():
    start_total_time = time.time()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # 2. VERİ ÖN İŞLEME kısmımız burası öğrenme açısını 20 ye çıkardık daha efektif sonuçlar için hocam.(we increased rotation to 20 degrees for better results)
    data_transforms = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(20),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    if not os.path.exists(DATA_DIR):
        print(f"HATA: '{DATA_DIR}' klasörü bulunamadı! Lütfen veri setini yükleyin.")
        return


    full_dataset = datasets.ImageFolder(DATA_DIR, transform=data_transforms)

    # 3. 10-FOLD CROSS VALIDATION kısmımız.
    kfold = KFold(n_splits=K_FOLDS, shuffle=True, random_state=42)
    fold_accuracies = []

    print(f"\nResNet34 ile {K_FOLDS}-Fold Cross Validation (Epochs: {NUM_EPOCHS})...")
    print("-" * 50)

    for fold, (train_ids, val_ids) in enumerate(kfold.split(full_dataset)):
        fold_start = time.time()

        train_sub = Subset(full_dataset, train_ids)
        val_sub = Subset(full_dataset, val_ids)

        train_loader = DataLoader(train_sub, batch_size=BATCH_SIZE, shuffle=True)
        val_loader = DataLoader(val_sub, batch_size=BATCH_SIZE, shuffle=False)

        model = get_model(device)
        optimizer = optim.Adam(model.parameters(), lr=0.0001)
        criterion = nn.CrossEntropyLoss()

        for epoch in range(NUM_EPOCHS):
            model.train()
            for inputs, labels in train_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

        # Validation
        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        accuracy = 100.0 * correct / total
        fold_accuracies.append(accuracy)

        fold_time = time.time() - fold_start
        print(f"Fold {fold+1}/{K_FOLDS} | Acc: {accuracy:.2f}% | Time: {fold_time:.1f}s")

    # SONUÇLAR (results)
    avg_acc = np.mean(fold_accuracies)
    total_time = (time.time() - start_total_time) / 60

    print("-" * 50)
    print(f"RESULTS:")
    print(f"Mean Accuracy: {avg_acc:.2f}%")
    print(f"Total Execution Time: {total_time:.2f} minutes")

    if total_time > 5.0:
        print("WARNING: Time limit exceeded!")
    else:
        print("SUCCESS: Completed within 5 minutes limit.")

if __name__ == "__main__":
    main()